kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: pure-file-nfs
  labels:
    kubernetes.io/cluster-service: "true"
provisioner: pure-csi 
parameters:
    backend: file
mountOptions:
      - nfsvers=3
      - tcp
