apiVersion: v1
kind: ConfigMap
metadata:
    name: pso-db-config
    namespace: {{ .Release.Namespace }}
data:
    {{- with .Values.database.nodeSelector | default .Values.nodeSelector }}
    nodeSelector: |
{{ toYaml . | indent 6 -}}
    {{- end }}
    {{- with .Values.database.affinity | default .Values.affinity }}
    affinity: |
{{ toYaml . | indent 6 -}}
    {{- end }}
    {{- with .Values.database.tolerations | default .Values.tolerations }}
    tolerations: |
{{ toYaml . | indent 6 -}}
    {{- end }}
    {{- if .Values.database.resources }}
    resources: |
{{ toYaml .Values.database.resources | indent 6 -}}
    {{- end }}
