kind: Role
apiVersion: {{ template "rbac.apiVersion" . }}
metadata:
  name: pso-db-runner
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "pure-csi.labels" . | indent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - services
  - endpoints
  - persistentvolumeclaims
  - events
  - configmaps
  - secrets
  verbs: ["create", "list", "watch", "delete", "get", "update"]
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
- apiGroups:
  - apps
  resources:
  - deployments
  - daemonsets
  - replicasets
  - statefulsets
  verbs: ["create", "list", "watch", "delete", "get", "update"]
- apiGroups:
  - batch
  resources:
  - jobs
  verbs: ["create", "list", "watch", "delete", "get", "update"]
- apiGroups:
  - monitoring.coreos.com
  resources:
  - servicemonitors
  verbs:
  - get
  - create
- apiGroups:
  - apps
  resourceNames:
  - pso-db-deployer
  - pso-cockroach-operator
  resources:
  - deployments/finalizers
  verbs:
  - update
- apiGroups:
  - pso.purestorage.com
  resources:
  - '*'
  verbs: ["create", "list", "watch", "delete", "get", "update"]

---

kind: RoleBinding
apiVersion: {{ template "rbac.apiVersion" . }}
metadata:
  name: pso-db-role
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "pure-csi.labels" . | indent 4 }}
subjects:
- kind: ServiceAccount
  name: {{ .Values.clusterrolebinding.serviceAccount.name }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: pso-db-runner
  apiGroup: rbac.authorization.k8s.io
