apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: intrusions.pso.purestorage.com
spec:
  group: pso.purestorage.com
  names:
    kind: Intrusion
    listKind: IntrusionList
    plural: intrusions
    singular: intrusion
    categories:
    - all
  scope: Namespaced
  subresources:
    status: {}
  additionalPrinterColumns:
    - JSONPath: .status.status
      description: The current status of the cluster
      name: Status
      type: string
    - JSONPath: .status.readyNodes
      description: The number of ready nodes in the cluster
      name: Ready
      type: string
    - JSONPath: .status.totalRanges
      description: The total number of ranges
      name: Ranges
      type: integer
    - JSONPath: .status.underreplicatedRanges
      description: The number of under-replicated ranges
      name: Under-Replicated
      type: integer
    - JSONPath: .status.unavailableRanges
      description: The number of unavailable ranges
      name: Unavailable
      type: integer
    - JSONPath: .status.asOf
      description: When the status was last updated
      name: As-Of
      type: string
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          properties:
            replicas:
              items:
                properties:
                  apiToken:
                    type: string
                  backendId:
                    type: string
                  backendType:
                    enum:
                    - Ephemeral
                    - FlashArray
                    - FlashBlade
                    - PVC
                    type: string
                  mgmtEndpoint:
                    type: string
                  volume:
                    type: string
                required:
                - backendType
                - volume
                type: object
              type: array
          required:
          - replicas
          type: object
        status:
          properties:
            asOf:
              type: string
            initialized:
              type: boolean
            readyNodes:
              type: string
            replicas:
              items:
                properties:
                  backendId:
                    type: string
                  backendType:
                    type: string
                  currentStatusStart:
                    type: string
                  decommission:
                    type: string
                  status:
                    type: string
                  volume:
                    type: string
                required:
                - backendType
                - currentStatusStart
                - status
                - volume
                type: object
              type: array
            status:
              type: string
            totalRanges:
              format: int64
              type: integer
            unavailableRanges:
              format: int64
              type: integer
            underreplicatedRanges:
              format: int64
              type: integer
          required:
          - asOf
          - initialized
          - status
          - readyNodes
          - totalRanges
          - underreplicatedRanges
          - unavailableRanges
          - replicas
          type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
